### ISSUE TITLE
member-not variant

### ISSUE THREAD

**Issue by sillvva** [brandonmcconnell/tailwindcss-members#2]
I added an additional variant called `member-not` which checks for the existence of the member, but that it does not match the specific qualifier (i.e. checked)

```ts
import plugin from 'tailwindcss/plugin.js';

const buildSelector = (modifier: string | null) => `.member${modifier ? `\\/${modifier}` : ''}`;

export default plugin(({ matchVariant }) => {
	const values = {
		// Default
		DEFAULT: "&",

		// Positional
		first: "&:first-child",
		last: "&:last-child",
		only: "&:only-child",
		odd: "&:nth-child(odd)",
		even: "&:nth-child(even)",
		"first-of-type": "&:first-of-type",
		"last-of-type": "&:last-of-type",
		"only-of-type": "&:only-of-type",

		// State
		visited: "&:visited",

		target: "&:target",
		open: "&:is([open], :popover-open)",

		// Forms
		default: "&:default",
		checked: "&:checked",
		indeterminate: "&:indeterminate",
		"placeholder-shown": "&:placeholder-shown",
		autofill: "&:autofill",
		optional: "&:optional",
		required: "&:required",
		valid: "&:valid",
		invalid: "&:invalid",
		"in-range": "&:in-range",
		"out-of-range": "&:out-of-range",
		"read-only": "&:read-only",

		// Content
		empty: "&:empty",

		// Interactive
		"focus-within": "&:focus-within",
		hover: "&:hover",
		focus: "&:focus",
		"focus-visible": "&:focus-visible",
		active: "&:active",
		enabled: "&:enabled",
		disabled: "&:disabled"
	} as const;

	matchVariant(
		"member",
		(rawValue, { modifier }) => {
			const value = rawValue || "&";
			const selector = buildMemberSelector(modifier);
			return `&:has(${selector}:is(${value.replaceAll("&", selector)})) { & }`;
		},
		{
			values
		}
	);

	matchVariant(
		"member-not",
		(rawValue, { modifier }) => {
			const value = rawValue || "&";
			const selector = buildMemberSelector(modifier);
			return `&:has(${selector}):not(:has(${selector}:is(${value.replaceAll("&", selector)}))) { & }`;
		},
		{
			values
		}
	);
})
```

Example:

This is a tab that uses a radio to determine if it is checked or not. 
- `member-checked` styles the active tab
- `member-not-checked:hover` adds a hover style to inactive tabs

```astro
<label
	class={cn(
		"h-11 max-w-[calc(100vw_-_160px)] cursor-pointer whitespace-nowrap bg-neutral-900 px-3 py-[11px] opacity-50",
		"border-x border-t-[2px] border-solid border-neutral-900 border-t-neutral-600",
		"member-checked:opacity-100 member-checked:border-t-secondary member-checked:border-x-neutral-700/50",
		"member-not-checked:hover:opacity-85 member-not-checked:hover:border-t-primary"
	)}
>
	<input class={`radio-${index} member hidden`} type="radio" name={uuid} checked={index === 1 ? "" : undefined} />
	<Fragment set:html={render} />
</label>
```

**Comment by brandonmcconnell** [comment]
Thanks for the PR, @sillvva!

I'm very interested in `not-` selectors, myself ([see here](https://github.com/tailwindlabs/tailwindcss/pull/7976#issuecomment-1472663929)).

The `not-` variant modifier is finally arriving in Tailwind CSS with the upcoming release of v4. While we could add support here in the meantime, there is currently no mechanism we can employ with the existing plugin system that will match specificity in the same way(s) that the `not-` variant modifier will in Tailwind CSS v4, so I think it would be best to wait until Tailwind CSS v4 for this, where it should work naturally.

If we were to employ this now, anyone who uses these modifiers would be subject to experiencing breaking changes once they upgrade to Tailwind CSS v4.

Alternatively, if you were to reshape your PR to refactor the plugin using `plugin.withOptions` to optionally support an options object like `{ EXPERIMENTAL: { notModifier: true } }` and a needed README section to explain the experimental option, I could see merging something like that sooner, as an opt-in feature.

Thank you again! I genuinely appreciate your interest in and contribution to [tailwindcss-members](https://github.com/brandonmcconnell/tailwindcss-members).

\- Brandon McConnell

**Comment by sillvva** [comment]
As far as I can tell, that PR was not about the member variant you created, though.

I'll just use this in my own projects for now.

**Comment by brandonmcconnell** [comment]
@sillvva Correct. That PR was to get the `not-` modifier added globally, which would work for all variants including `member`. In other words, `member-not-` and `group-not-` are **_already_** supported in Tailwind CSS v4, so once there's a stable release, you will be able to use `member-not-`, `group-not-`, etc. simply by upgrading to v4, without any additional changes needed.

I'm still open to adding your changes to this package if you refactor them as an experimental option, as I mentioned :)

**Comment by sillvva** [comment]
Wouldn't it be more like `has-[.member]-not-has-[.member]-checked`? The variant I'm using is like this:

```ts
return `&:has(${selector}):not(:has(${selector}:is(${value.replaceAll("&", selector)}))) { & }`;
// &:has(.member):not(:has(.member:is(.member:checked)))
```

Basically, the `&` element has a `.member` element, but it does not have a checked `.member` element.

Also this is just an **issue** to bring up the option of including this. Not a PR.

**Comment by brandonmcconnell** [comment]
@sillvva Because `member` takes care of all of the `has` logic under the hood, you wouldn't need to use `has` explicitly.

The usage would simply be `member-not-checked`.
